package server

import (
	"context"

	pb "github.com/AbhinayAmbati/distributed_cache_system/api/proto"
	"google.golang.org/grpc"
)

// CacheServiceServer is the server API for CacheService.
// This would normally be generated by protoc-gen-go-grpc.
type CacheServiceServer interface {
	Get(context.Context, *pb.GetRequest) (*pb.GetResponse, error)
	Set(context.Context, *pb.SetRequest) (*pb.SetResponse, error)
	Delete(context.Context, *pb.DeleteRequest) (*pb.DeleteResponse, error)
	Expire(context.Context, *pb.ExpireRequest) (*pb.ExpireResponse, error)
	Keys(context.Context, *pb.KeysRequest) (*pb.KeysResponse, error)
	Ping(context.Context, *pb.PingRequest) (*pb.PingResponse, error)
	Replicate(context.Context, *pb.ReplicateRequest) (*pb.ReplicateResponse, error)
	TransferKeys(*pb.TransferKeysRequest, CacheService_TransferKeysServer) error
}

// CacheService_TransferKeysServer is the server-side streaming interface for TransferKeys.
type CacheService_TransferKeysServer interface {
	Send(*pb.KeyValuePair) error
	grpc.ServerStream
}

type transferKeysServer struct {
	grpc.ServerStream
}

func (s *transferKeysServer) Send(kv *pb.KeyValuePair) error {
	return s.ServerStream.SendMsg(kv)
}

// CacheService_TransferKeysClient is the client-side streaming interface for TransferKeys.
type CacheService_TransferKeysClient interface {
	Recv() (*pb.KeyValuePair, error)
	grpc.ClientStream
}

type transferKeysClient struct {
	grpc.ClientStream
}

func (c *transferKeysClient) Recv() (*pb.KeyValuePair, error) {
	kv := &pb.KeyValuePair{}
	if err := c.ClientStream.RecvMsg(kv); err != nil {
		return nil, err
	}
	return kv, nil
}

// ServiceDesc is the grpc.ServiceDesc for CacheService.
var ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    handleGet,
		},
		{
			MethodName: "Set",
			Handler:    handleSet,
		},
		{
			MethodName: "Delete",
			Handler:    handleDelete,
		},
		{
			MethodName: "Expire",
			Handler:    handleExpire,
		},
		{
			MethodName: "Keys",
			Handler:    handleKeys,
		},
		{
			MethodName: "Ping",
			Handler:    handlePing,
		},
		{
			MethodName: "Replicate",
			Handler:    handleReplicate,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferKeys",
			Handler:       handleTransferKeys,
			ServerStreams:  true,
		},
	},
	Metadata: "cache.proto",
}

// RegisterCacheServiceServer registers the CacheService with the gRPC server.
func RegisterCacheServiceServer(s *grpc.Server, srv CacheServiceServer) {
	s.RegisterService(&ServiceDesc, srv)
}

// --- Handler wrappers (decode request, call method, return response) ---

func handleGet(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	req := &pb.GetRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Get(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Get"}
	return interceptor(ctx, req, info, func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Get(ctx, r.(*pb.GetRequest))
	})
}

func handleSet(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	req := &pb.SetRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Set(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Set"}
	return interceptor(ctx, req, info, func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Set(ctx, r.(*pb.SetRequest))
	})
}

func handleDelete(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	req := &pb.DeleteRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Delete(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Delete"}
	return interceptor(ctx, req, info, func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Delete(ctx, r.(*pb.DeleteRequest))
	})
}

func handleExpire(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	req := &pb.ExpireRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Expire(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Expire"}
	return interceptor(ctx, req, info, func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Expire(ctx, r.(*pb.ExpireRequest))
	})
}

func handleKeys(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	req := &pb.KeysRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Keys(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Keys"}
	return interceptor(ctx, req, info, func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Keys(ctx, r.(*pb.KeysRequest))
	})
}

func handlePing(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	req := &pb.PingRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Ping(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Ping"}
	return interceptor(ctx, req, info, func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Ping(ctx, r.(*pb.PingRequest))
	})
}

func handleReplicate(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	req := &pb.ReplicateRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Replicate(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Replicate"}
	return interceptor(ctx, req, info, func(ctx context.Context, r interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Replicate(ctx, r.(*pb.ReplicateRequest))
	})
}

func handleTransferKeys(srv interface{}, stream grpc.ServerStream) error {
	req := &pb.TransferKeysRequest{}
	if err := stream.RecvMsg(req); err != nil {
		return err
	}
	return srv.(CacheServiceServer).TransferKeys(req, &transferKeysServer{stream})
}
