// Package proto defines the message types and service interface for the cache.
// These are hand-written Go equivalents of the proto definitions.
// In production, these would be generated by protoc from cache.proto.
package proto

// --- Client-facing messages ---

// GetRequest is a request to retrieve a value by key.
type GetRequest struct {
	Key string
}

// GetResponse is the response for a Get operation.
type GetResponse struct {
	Key   string
	Value []byte
	Found bool
	TtlMs int64 // Remaining TTL in milliseconds, 0 = no expiry.
	IsHot bool  // Hint: this key is detected as hot.
}

// SetRequest is a request to store a key-value pair.
type SetRequest struct {
	Key   string
	Value []byte
	TtlMs int64 // TTL in milliseconds, 0 = no expiry.
}

// SetResponse is the response for a Set operation.
type SetResponse struct {
	Success bool
}

// DeleteRequest is a request to remove a key.
type DeleteRequest struct {
	Key string
}

// DeleteResponse is the response for a Delete operation.
type DeleteResponse struct {
	Existed bool
}

// ExpireRequest is a request to update the TTL on a key.
type ExpireRequest struct {
	Key   string
	TtlMs int64 // New TTL in milliseconds, 0 = remove expiry.
}

// ExpireResponse is the response for an Expire operation.
type ExpireResponse struct {
	Found bool
}

// KeysRequest is a request to list keys.
type KeysRequest struct {
	Pattern string // Optional glob pattern (reserved for future).
}

// KeysResponse is the response for a Keys operation.
type KeysResponse struct {
	Keys []string
}

// PingRequest is a health check request.
type PingRequest struct{}

// PingResponse is a health check response.
type PingResponse struct {
	NodeId    string
	UptimeMs  int64
	KeysCount int64
}

// --- Internal replication messages ---

// Operation represents the type of replicated operation.
type Operation int

const (
	OpSet    Operation = 0
	OpDelete Operation = 1
)

// ReplicateRequest is an internal request to replicate a write to a secondary.
type ReplicateRequest struct {
	Key        string
	Value      []byte
	TtlMs      int64
	Sequence   uint64    // Monotonic sequence number for ordering.
	SourceNode string    // Node that originated the write.
	Op         Operation // SET or DELETE.
}

// ReplicateResponse is the response for a Replicate operation.
type ReplicateResponse struct {
	Success bool
}

// TransferKeysRequest is an internal request to transfer keys in a hash range.
type TransferKeysRequest struct {
	RangeStart     uint64
	RangeEnd       uint64
	RequestingNode string
}

// KeyValuePair is a single key-value entry used in bulk transfers.
type KeyValuePair struct {
	Key   string
	Value []byte
	TtlMs int64
}
